version: "1.1"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app/
    ports:
      - 4200:4200
    depends_on:
      - backend

volumes:
  postgres_data:
