version: "1.1"

services:
  backend:
    build: ./backend
    # command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
  #   env_file:
  #     - ./backend/.docker_backend.env
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./backend/.docker_db.env
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app/
    ports:
      - 4200:4200
    # depends_on:
    #   - backend

# volumes:
#   postgres_data:
