"""Create 'teams' table and add its relationship with 'coaches'

Revision ID: 15ea7e7fffb0
Revises: 2c9426b8ad8a
Create Date: 2023-09-01 19:53:17.878624

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "15ea7e7fffb0"
down_revision = "2c9426b8ad8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
