"""Make matches.goals_* nullable

Revision ID: 1c2a69e96fe1
Revises: 8485b858156d
Create Date: 2023-11-01 15:26:17.150772

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c2a69e96fe1"
down_revision = "8485b858156d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches", "goals_scored", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "matches", "goals_conceded", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("matches", "notes", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches", "goals_conceded", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "matches", "goals_scored", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("matches", "notes", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
