"""Add an is_own_event field to the matchevents table

Revision ID: 2fa891c8c8cb
Revises: 450e9efe6417
Create Date: 2023-11-19 09:56:43.123796

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2fa891c8c8cb"
down_revision = "450e9efe6417"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matchevents", sa.Column("is_own_event", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchevents", "is_own_event")
    # ### end Alembic commands ###
