"""Create 'matches_players' table and add its relationship with 'players' and 'matches'

Revision ID: 4397df2634cd
Revises: bb3ac5550f20
Create Date: 2023-09-03 19:57:54.163673

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4397df2634cd"
down_revision = "bb3ac5550f20"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches_players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("starter", sa.Boolean(), nullable=False),
        sa.Column("minutes_played", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_matches_players_id"), "matches_players", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matches_players_id"), table_name="matches_players")
    op.drop_table("matches_players")
    # ### end Alembic commands ###
