"""Add ondelete cascade to foreign keys constraints in association tables

Revision ID: 5fe72de40c11
Revises: a7cf8e14ac32
Create Date: 2023-10-16 17:16:00.767974

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5fe72de40c11"
down_revision = "a7cf8e14ac32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "matches_players_match_id_fkey", "matches_players", type_="foreignkey"
    )
    op.drop_constraint(
        "matches_players_player_id_fkey", "matches_players", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "matches_players", "matches", ["match_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "matches_players",
        "players",
        ["player_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "meetings_users_user_id_fkey", "meetings_users", type_="foreignkey"
    )
    op.drop_constraint(
        "meetings_users_meeting_id_fkey", "meetings_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "meetings_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "meetings_users", "meetings", ["meeting_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "trainings_players_training_id_fkey", "trainings_players", type_="foreignkey"
    )
    op.drop_constraint(
        "trainings_players_player_id_fkey", "trainings_players", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "trainings_players",
        "trainings",
        ["training_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "trainings_players",
        "players",
        ["player_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "trainings_players_player_id_fkey", "trainings_players", type_="foreignkey"
    )
    op.drop_constraint(
        "trainings_players_training_id_fkey", "trainings_players", type_="foreignkey"
    )
    op.create_foreign_key(
        "trainings_players_player_id_fkey",
        "trainings_players",
        "players",
        ["player_id"],
        ["user_id"],
    )
    op.create_foreign_key(
        "trainings_players_training_id_fkey",
        "trainings_players",
        "trainings",
        ["training_id"],
        ["id"],
    )
    op.drop_constraint(
        "meetings_users_meeting_id_fkey", "meetings_users", type_="foreignkey"
    )
    op.drop_constraint("meetings_users", "meetings_users", type_="foreignkey")
    op.create_foreign_key(
        "meetings_users_meeting_id_fkey",
        "meetings_users",
        "meetings",
        ["meeting_id"],
        ["id"],
    )
    op.create_foreign_key(
        "meetings_users_user_id_fkey", "meetings_users", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(
        "matches_players_player_id_fkey", "matches_players", type_="foreignkey"
    )
    op.drop_constraint(
        "matches_players_match_id_fkey", "matches_players", type_="foreignkey"
    )
    op.create_foreign_key(
        "matches_players_player_id_fkey",
        "matches_players",
        "players",
        ["player_id"],
        ["user_id"],
    )
    op.create_foreign_key(
        "matches_players_match_id_fkey",
        "matches_players",
        "matches",
        ["match_id"],
        ["id"],
    )
    # ### end Alembic commands ###
