"""Make matches_players rating nullable and update model's defaults

Revision ID: 8485b858156d
Revises: dea6babd480e
Create Date: 2023-11-01 10:43:15.732710

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8485b858156d"
down_revision = "dea6babd480e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches_players",
        "is_starter",
        server_default=sa.sql.false(),
    )
    op.alter_column(
        "matches_players",
        "rating",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "matches_players",
        "minutes_played",
        server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches_players",
        "is_starter",
        server_default=sa.sql.true(),
    )
    op.alter_column(
        "matches_players",
        "rating",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "matches_players",
        "minutes_played",
        server_default=None,
    )
    # ### end Alembic commands ###
