"""Update User model

Revision ID: 84ebe8776f0b
Revises: 9168b4e9d52f
Create Date: 2023-07-06 20:06:39.409516

"""

# pylint: skip-file
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84ebe8776f0b"
down_revision = "9168b4e9d52f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
