"""Make teams.coach_id and players.team_id nullable

Revision ID: a7cf8e14ac32
Revises: 9000167b8538
Create Date: 2023-10-16 13:51:13.448020

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a7cf8e14ac32"
down_revision = "9000167b8538"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("players", "team_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("players_team_id_fkey", "players", type_="foreignkey")
    op.create_foreign_key(
        None, "players", "teams", ["team_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column("teams", "coach_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("teams_coach_id_fkey", "teams", type_="foreignkey")
    op.create_foreign_key(
        None, "teams", "coaches", ["coach_id"], ["user_id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("teams", "coach_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("teams_coach_id_fkey", "teams", type_="foreignkey")
    op.create_foreign_key(
        "teams_coach_id_fkey", "teams", "coaches", ["coach_id"], ["user_id"]
    )
    op.alter_column("players", "team_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("players_team_id_fkey", "players", type_="foreignkey")
    op.create_foreign_key(
        "players_team_id_fkey", "players", "teams", ["team_id"], ["id"]
    )
    # ### end Alembic commands ###
