"""Create 'matches' table and add its relationship with 'teams'

Revision ID: bb3ac5550f20
Revises: 8a8f2b553b47
Create Date: 2023-09-03 10:50:48.844276

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb3ac5550f20"
down_revision = "8a8f2b553b47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("opponent", sa.String(), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("goals_scored", sa.Integer(), nullable=False),
        sa.Column("goals_conceded", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_id"), "matches", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matches_id"), table_name="matches")
    op.drop_table("matches")
    # ### end Alembic commands ###
