"""Create 'trainings_players' table and add its relationship with 'trainings' and 'matches'

Revision ID: bd4a29c5530d
Revises: 08db87392f1a
Create Date: 2023-09-05 20:59:31.936263

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd4a29c5530d"
down_revision = "08db87392f1a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trainings_players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("training_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("presence", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trainings_players_id"), "trainings_players", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trainings_players_id"), table_name="trainings_players")
    op.drop_table("trainings_players")
    # ### end Alembic commands ###
