"""Create 'players' table and add its relationship with 'teams'

Revision ID: ca4db8f01700
Revises: 15ea7e7fffb0
Create Date: 2023-09-02 15:03:50.448480

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca4db8f01700"
down_revision = "15ea7e7fffb0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("date_of_joining", sa.Date(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("is_injured", sa.Boolean(), nullable=False),
        sa.Column("diet", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("players")
    # ### end Alembic commands ###
