"""Set nullable for meetings.notes and injuries.prescriptions

Revision ID: d63552df296b
Revises: 84fba46e31a8
Create Date: 2023-09-07 16:13:01.864778

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d63552df296b"
down_revision = "84fba46e31a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "injuries", "prescriptions", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("meetings", "notes", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("meetings", "notes", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "injuries", "prescriptions", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
