"""Make players.notes nullable

Revision ID: dea6babd480e
Revises: 5fe72de40c11
Create Date: 2023-10-20 21:49:53.000809

"""

# pylint: skip-file
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dea6babd480e"
down_revision = "5fe72de40c11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("players", "notes", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("players", "notes", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
